name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # hoặc branch bạn dùng

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/DucLai/Vietnamese_NER space
          rsync -av --exclude '.git' ./ space/
          cd space
          git add .
          git commit -m "Auto-deploy from GitHub" || echo "No changes to commit"
          git push https://DucLai:${HF_TOKEN}@huggingface.co/spaces/DucLai/Vietnamese_NER HEAD
